{{ if .Values.airflow.dags.gitSync.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.airflow.dags.gitSync.credentialsSecret | default "~" }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: kubernetes-external-secrets
  data:
    - key: {{ .Values.gitSync.secret_path }}
      name: GIT_SYNC_USERNAME
      property: {{ .Values.gitSync.username_key }}
    - key: homestead-secrets/data/github/vault-godmode-token
      name: GIT_SYNC_PASSWORD
      property: {{ .Values.gitSync.password_key }}
{{ end }}